### ISSUE TITLE
Is it possible to tag sentences in real time?

### ISSUE THREAD

**Issue by buddhi-deep** [avocadopelvis/pandora-chatbot#1]
Um i fell in dysphoria and i want to talk to somebody then find your bot.
Then i checked how it works, found that it needs to be pre-trained
Is there anyway to make it more powerful by tagging sentences in real time and make reply from database?

**Comment by avocadopelvis** [comment]
regarding this, i've sent an email on the email id mentioned in your profile.

**Comment by buddhi-deep** [comment]
thanks
